import assert from "node:assert/strict";
import test from "node:test";

import { changedRetellFields, createRetellClient, retellFingerprints } from "./providers.mjs";
import { createFakeRetell } from "./test-support/fake-retell.mjs";

const HAND_PROMPT = "# ROLE\nHand-written in the Retell dashboard.\n# ACCOUNTS RECEIVABLE\n...";
const APP_PROMPT = "# ROLE\nGenerated by the app.";
const PHONE = "+12408850416";

const appTool = (name, extra = {}) => ({ type: "custom", name, description: name, ...extra });
const APP_TOOLS = [appTool("end_call"), appTool("message_take"), appTool("transfer_call_1", { number: "+12402928505" })];

function appConfig(overrides = {}) {
  return {
    prompt: APP_PROMPT,
    tools: APP_TOOLS,
    voice: "11labs-Hailey",
    ambientSound: "convention-hall",
    knowledgeBaseIds: ["kb-app"],
    retellAgent: { max_call_duration_ms: 600000 },
    ...overrides,
  };
}

// Samantha as found in production on 2026-09-24: v0 and v1 published, the
// phone pinned to v1, a hand-written prompt, and a draft v2 whose model
// someone changed in the dashboard without publishing.
function seedSamantha(fake, { draft = true } = {}) {
  const llm = {
    general_prompt: HAND_PROMPT,
    begin_message: "Thanks for calling C W R.",
    model: "gpt-5.6-terra",
    general_tools: [
      appTool("end_call"),
      appTool("transfer_call_1", { number: "+17035550102" }),
      appTool("transfer_call_3", { number: "+17035550199" }),
      appTool("lookup_invoice"),
    ],
    knowledge_base_ids: ["kb-1", "kb-2"],
  };
  const agent = { voice_id: "11labs-Hailey", ambient_sound: "convention-hall", agent_name: "Samantha" };
  const versions = [
    { published: true, agent, llm },
    { published: true, agent, llm },
    ...(draft ? [{ published: false, agent, llm: { ...llm, model: "gpt-5" } }] : []),
  ];
  const ids = fake.seedAgent({ versions });
  fake.seedPhone(PHONE, ids.agentId, 1);
  return ids;
}

function client(fake) {
  return createRetellClient({ apiKey: "retell-key", fetchImpl: fake.fetchImpl });
}

function save(fake, agentId, overrides = {}) {
  return client(fake).upsertAgent({
    retellAgentId: agentId,
    symanticAgentId: "agent-samantha",
    agentName: "Samantha",
    greeting: "Thanks for calling CWR Solutions.",
    config: appConfig(),
    ...overrides,
  });
}

// What an admin does by hand in the Retell dashboard: new draft from the
// live version, edit it, publish.
async function dashboardEditAndPublish(fake, agentId, edit) {
  const live = fake.versions(agentId).filter((version) => version.is_published).at(-1);
  await fake.fetchImpl(`https://api.retellai.com/create-agent-version/${agentId}`, {
    method: "POST",
    body: JSON.stringify({ base_version: live.version }),
  });
  fake.dashboardEditDraft(agentId, edit);
  fake.dashboardPublishLatest(agentId);
}

test("a save never sends response_engine to an agent that already has published versions (the Sep 17 production failure)", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const result = await save(fake, agentId);

  assert.ok(Number.isInteger(result.publishedVersion));
  const agentUpdates = fake.requests.filter((request) => request.path.startsWith("/update-agent/"));
  assert.ok(agentUpdates.length > 0);
  for (const update of agentUpdates) assert.equal(update.body.response_engine, undefined);
});

test("sync is one-way: the app's prompt, greeting, tools and knowledge bases replace everything that was in Retell", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  await save(fake, agentId);

  const live = fake.answering(PHONE);
  assert.equal(live.llm.general_prompt, APP_PROMPT);
  assert.equal(live.llm.begin_message, "Thanks for calling CWR Solutions.");
  assert.deepEqual(live.llm.general_tools.map((tool) => tool.name), ["end_call", "message_take", "transfer_call_1"]);
  assert.doesNotMatch(JSON.stringify(live.llm.general_tools), /555010[29]/);
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-app"]);
  // A field the app doesn't manage stays at its live value.
  assert.equal(live.llm.model, "gpt-5.6-terra");
});

test("unpublished dashboard edits are discarded silently: the save starts from the live version, so the draft's model change never goes live", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  const result = await save(fake, agentId);

  assert.equal(result.publishedVersion, 2);
  const live = fake.answering(PHONE);
  assert.equal(live.agent.version, 2);
  assert.equal(live.llm.model, "gpt-5.6-terra");
  assert.equal(live.llm.general_prompt, APP_PROMPT);
});

test("the phone stops being pinned to one version: after a save it follows latest_published and callers hear the save", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  assert.equal(fake.answering(PHONE).agent.version, 1);

  const result = await save(fake, agentId);

  const live = fake.answering(PHONE);
  assert.equal(live.binding, "latest_published");
  assert.equal(live.agent.version, result.publishedVersion);
});

test("a dashboard publish after an app save goes live too, since the number follows latest_published", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  await save(fake, agentId);

  await dashboardEditAndPublish(fake, agentId, { llm: { general_prompt: "# ROLE\nEdited by hand in Retell." } });

  assert.equal(fake.answering(PHONE).llm.general_prompt, "# ROLE\nEdited by hand in Retell.");
});

test("the next app save replaces a prompt someone edited and published in Retell", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  await save(fake, agentId);
  await dashboardEditAndPublish(fake, agentId, { llm: { general_prompt: "# ROLE\nEdited by hand in Retell." } });

  await save(fake, agentId, { config: appConfig({ prompt: "# ROLE\nSaved again from the app." }) });

  assert.equal(fake.answering(PHONE).llm.general_prompt, "# ROLE\nSaved again from the app.");
});

test("saving twice in a row works: each save makes a new draft from the live version and publishes it", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const first = await save(fake, agentId);
  const second = await save(fake, agentId, { config: appConfig({ ambientSound: "" }) });

  assert.equal(second.publishedVersion, first.publishedVersion + 1);
  assert.equal(fake.answering(PHONE).agent.ambient_sound, null);
});

test("fingerprints: unchanged right after an app save, a dashboard edit is reported by field, and the next save resets the baseline", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  const retell = client(fake);
  const saved = await save(fake, agentId);

  const afterSave = await retell.readLivePublished(agentId);
  assert.deepEqual(changedRetellFields(saved.fingerprints, retellFingerprints(afterSave.agent, afterSave.llm)), []);

  await dashboardEditAndPublish(fake, agentId, {
    agent: { voice_id: "11labs-Adrian" },
    llm: { general_prompt: "# ROLE\nEdited by hand in Retell.", model: "gpt-5" },
  });
  const afterEdit = await retell.readLivePublished(agentId);
  assert.deepEqual(
    changedRetellFields(saved.fingerprints, retellFingerprints(afterEdit.agent, afterEdit.llm)),
    ["agent.voice_id", "llm.general_prompt", "llm.model"],
  );

  const resaved = await save(fake, agentId);
  const afterResave = await retell.readLivePublished(agentId);
  assert.deepEqual(changedRetellFields(resaved.fingerprints, retellFingerprints(afterResave.agent, afterResave.llm)), []);
});

test("an unpublished dashboard draft doesn't count as a manual edit - callers don't hear it", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  const retell = client(fake);
  const saved = await save(fake, agentId);

  await fake.fetchImpl(`https://api.retellai.com/create-agent-version/${agentId}`, {
    method: "POST",
    body: JSON.stringify({ base_version: saved.publishedVersion }),
  });
  fake.dashboardEditDraft(agentId, { llm: { general_prompt: "# ROLE\nNot published." } });

  const live = await retell.readLivePublished(agentId);
  assert.deepEqual(changedRetellFields(saved.fingerprints, retellFingerprints(live.agent, live.llm)), []);
});

test("a new agent is published at creation, its imported number follows latest_published, and the next save goes live", async () => {
  const fake = createFakeRetell();
  const retell = createRetellClient({ apiKey: "retell-key", fetchImpl: fake.fetchImpl, terminationUri: "sip.telnyx.com" });

  const created = await retell.upsertAgent({
    symanticAgentId: "agent-new",
    agentName: "Nova",
    greeting: "Hello.",
    config: appConfig(),
  });
  await retell.importPhoneNumber({ phoneNumber: "+15550001111", retellAgentId: created.retellAgentId });

  assert.equal(created.publishedVersion, 0);
  assert.ok(created.fingerprints["llm.general_prompt"]);
  const live = fake.answering("+15550001111");
  assert.equal(live.binding, "latest_published");
  assert.equal(live.llm.general_prompt, APP_PROMPT);

  await retell.upsertAgent({
    retellAgentId: created.retellAgentId,
    symanticAgentId: "agent-new",
    agentName: "Nova",
    greeting: "Hello.",
    config: appConfig({ prompt: "# ROLE\nSecond save." }),
  });
  assert.equal(fake.answering("+15550001111").llm.general_prompt, "# ROLE\nSecond save.");
});

test("a knowledge base edit reaches callers on a versioned agent, and returns fresh fingerprints", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const published = await client(fake).pushKnowledgeBaseIds(agentId, ["kb-new"]);

  const live = fake.answering(PHONE);
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-new"]);
  assert.equal(live.binding, "latest_published");
  assert.ok(published.fingerprints["llm.knowledge_base_ids"]);
});

test("a knowledge base edit also discards unpublished dashboard edits instead of publishing them", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  await client(fake).pushKnowledgeBaseIds(agentId, ["kb-new"]);

  const live = fake.answering(PHONE);
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-new"]);
  assert.equal(live.llm.model, "gpt-5.6-terra");
});
