import assert from "node:assert/strict";
import test from "node:test";

import { createRetellClient, promptHash } from "./providers.mjs";
import { createFakeRetell } from "./test-support/fake-retell.mjs";

const HAND_PROMPT = "# ROLE\nHand-written in the Retell dashboard.\n# ACCOUNTS RECEIVABLE\n...";
const APP_PROMPT = "# ROLE\nGenerated by the app.";
const PHONE = "+12408850416";

const appTool = (name, extra = {}) => ({ type: "custom", name, description: name, ...extra });
const APP_TOOLS = [appTool("end_call"), appTool("message_take"), appTool("transfer_call_1", { number: "+12402928505" })];

function appConfig(overrides = {}) {
  return {
    prompt: APP_PROMPT,
    tools: APP_TOOLS,
    voice: "11labs-Hailey",
    ambientSound: "convention-hall",
    knowledgeBaseIds: ["kb-app"],
    retellAgent: { max_call_duration_ms: 600000 },
    ...overrides,
  };
}

// Samantha as found in production on 2026-09-24: v0 and v1 published, the
// phone pinned to v1, and a draft v2 whose model someone changed in the
// dashboard without publishing.
function seedSamantha(fake, { draft = true } = {}) {
  const llm = {
    general_prompt: HAND_PROMPT,
    begin_message: "Thanks for calling C W R.",
    model: "gpt-5.6-terra",
    general_tools: [
      appTool("end_call"),
      appTool("transfer_call_1", { number: "+17035550102" }),
      appTool("transfer_call_3", { number: "+17035550199" }),
      appTool("lookup_invoice"),
    ],
    knowledge_base_ids: ["kb-1", "kb-2"],
  };
  const agent = { voice_id: "11labs-Hailey", ambient_sound: "convention-hall", agent_name: "Samantha" };
  const versions = [
    { published: true, agent, llm },
    { published: true, agent, llm },
    ...(draft ? [{ published: false, agent, llm: { ...llm, model: "gpt-5" } }] : []),
  ];
  const ids = fake.seedAgent({ versions });
  fake.seedPhone(PHONE, ids.agentId, 1);
  return ids;
}

function client(fake) {
  return createRetellClient({ apiKey: "retell-key", fetchImpl: fake.fetchImpl });
}

function save(fake, agentId, overrides = {}) {
  return client(fake).upsertAgent({
    retellAgentId: agentId,
    symanticAgentId: "agent-samantha",
    agentName: "Samantha",
    greeting: "Thanks for calling CWR Solutions.",
    config: appConfig(),
    ...overrides,
  });
}

test("a save never sends response_engine to an agent that already has published versions (the Sep 17 production failure)", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const result = await save(fake, agentId, { promptSource: "retell" });

  assert.equal(result.published, true);
  const agentUpdates = fake.requests.filter((request) => request.path.startsWith("/update-agent/"));
  assert.ok(agentUpdates.length > 0);
  for (const update of agentUpdates) assert.equal(update.body.response_engine, undefined);
});

test("a hand-written Retell prompt is kept: the agent switches to promptSource retell and only app-owned fields change", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  // No record of what the app last pushed, and the live prompt isn't the
  // app's - exactly Samantha's case.
  const result = await save(fake, agentId);

  assert.equal(result.promptSource, "retell");
  assert.equal(result.pushedPromptHash, undefined);
  const live = fake.answering(PHONE);
  assert.equal(live.llm.general_prompt, HAND_PROMPT);
  assert.equal(live.llm.begin_message, "Thanks for calling C W R.");
  assert.equal(live.llm.model, "gpt-5.6-terra");
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-app"]);
});

test("the app's transfer tools replace the old ones (dropping the fake 555 numbers) while a tool added by hand in Retell survives", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  await save(fake, agentId, { promptSource: "retell" });

  const names = fake.answering(PHONE).llm.general_tools.map((tool) => tool.name);
  assert.deepEqual(names.sort(), ["end_call", "lookup_invoice", "message_take", "transfer_call_1"]);
  const numbers = JSON.stringify(fake.answering(PHONE).llm.general_tools);
  assert.doesNotMatch(numbers, /555010[29]/);
});

test("the phone stops being pinned to one version: after a save it follows latest_published and callers hear the save", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  assert.equal(fake.answering(PHONE).agent.version, 1);

  const result = await save(fake, agentId, { promptSource: "retell" });

  const live = fake.answering(PHONE);
  assert.equal(live.binding, "latest_published");
  assert.equal(live.agent.version, result.publishedVersion);
  assert.ok(result.publishedVersion > 1);
});

test("unpublished dashboard edits stop the save before publishing and are reported, so nothing half-finished goes live silently", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  const result = await save(fake, agentId, { promptSource: "retell" });

  assert.equal(result.published, false);
  assert.deepEqual(result.pendingRetellEdits.map((edit) => `${edit.scope}.${edit.field}`), ["llm.model"]);
  assert.equal(result.pendingRetellEdits[0].published, "gpt-5.6-terra");
  assert.equal(result.pendingRetellEdits[0].draft, "gpt-5");
  // Callers still hear v1, untouched.
  assert.equal(fake.answering(PHONE).agent.version, 1);
  assert.equal(fake.answering(PHONE).llm.model, "gpt-5.6-terra");
});

test("choosing Discard resets the dashboard's unpublished edits to the live values, then publishes the app's changes", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  const result = await save(fake, agentId, { promptSource: "retell", retellEditsDecision: "discard" });

  assert.equal(result.published, true);
  const live = fake.answering(PHONE);
  assert.equal(live.agent.version, 2);
  assert.equal(live.llm.model, "gpt-5.6-terra");
  assert.equal(live.llm.general_prompt, HAND_PROMPT);
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-app"]);
});

test("choosing Include publishes the dashboard's unpublished edits together with the app's changes", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  await save(fake, agentId, { promptSource: "retell", retellEditsDecision: "include" });

  assert.equal(fake.answering(PHONE).llm.model, "gpt-5");
});

test("an app-owned prompt is pushed and published, and the pushed hash is returned for the next save's edit check", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  const first = await save(fake, agentId, { overwriteRetellPrompt: true });
  assert.equal(first.promptSource, "app");
  assert.equal(first.pushedPromptHash, promptHash(APP_PROMPT));
  assert.equal(fake.answering(PHONE).llm.general_prompt, APP_PROMPT);

  const second = await save(fake, agentId, {
    lastPushedPromptHash: first.pushedPromptHash,
    config: appConfig({ prompt: "# ROLE\nGenerated again, with new hours." }),
  });

  assert.equal(second.promptSource, "app");
  assert.equal(second.published, true);
  assert.equal(fake.answering(PHONE).llm.general_prompt, "# ROLE\nGenerated again, with new hours.");
});

test("a prompt edited and published in the Retell dashboard after the app's last push switches the agent to promptSource retell instead of being overwritten", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });
  const first = await save(fake, agentId, { overwriteRetellPrompt: true });

  // Someone edits in the dashboard (e.g. while the app is down) and publishes.
  const versions = fake.versions(agentId);
  assert.ok(versions.at(-1).is_published);
  // Dashboard flow: new draft from live, edit, publish.
  await fake.fetchImpl(`https://api.retellai.com/create-agent-version/${agentId}`, {
    method: "POST",
    body: JSON.stringify({ base_version: versions.at(-1).version }),
  });
  fake.dashboardEditDraft(agentId, { llm: { general_prompt: "# ROLE\nEdited by hand in Retell." } });
  fake.dashboardPublishLatest(agentId);
  assert.equal(fake.answering(PHONE).llm.general_prompt, "# ROLE\nEdited by hand in Retell.");

  const second = await save(fake, agentId, { lastPushedPromptHash: first.pushedPromptHash });

  assert.equal(second.promptSource, "retell");
  assert.equal(fake.answering(PHONE).llm.general_prompt, "# ROLE\nEdited by hand in Retell.");
});

test("overwriteRetellPrompt replaces a hand-written prompt on purpose", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const result = await save(fake, agentId, { promptSource: "retell", overwriteRetellPrompt: true });

  assert.equal(result.promptSource, "app");
  assert.equal(fake.answering(PHONE).llm.general_prompt, APP_PROMPT);
});

test("saving twice in a row works: each save makes a new draft from the live version and publishes it", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  const first = await save(fake, agentId, { promptSource: "retell" });
  const second = await save(fake, agentId, { promptSource: "retell", config: appConfig({ ambientSound: "" }) });

  assert.equal(second.publishedVersion, first.publishedVersion + 1);
  assert.equal(fake.answering(PHONE).agent.ambient_sound, null);
});

test("a new agent is published at creation and its imported number follows latest_published", async () => {
  const fake = createFakeRetell();
  const retell = createRetellClient({ apiKey: "retell-key", fetchImpl: fake.fetchImpl, terminationUri: "sip.telnyx.com" });

  const created = await retell.upsertAgent({
    symanticAgentId: "agent-new",
    agentName: "Nova",
    greeting: "Hello.",
    config: appConfig(),
  });
  await retell.importPhoneNumber({ phoneNumber: "+15550001111", retellAgentId: created.retellAgentId });

  assert.equal(created.published, true);
  assert.equal(created.promptSource, "app");
  const live = fake.answering("+15550001111");
  assert.equal(live.binding, "latest_published");
  assert.equal(live.llm.general_prompt, APP_PROMPT);

  // And the very next save goes live too - no pinned version, no engine error.
  const saved = await retell.upsertAgent({
    retellAgentId: created.retellAgentId,
    symanticAgentId: "agent-new",
    agentName: "Nova",
    greeting: "Hello.",
    config: appConfig({ prompt: "# ROLE\nSecond save." }),
    lastPushedPromptHash: created.pushedPromptHash,
  });
  assert.equal(saved.published, true);
  assert.equal(fake.answering("+15550001111").llm.general_prompt, "# ROLE\nSecond save.");
});

test("a knowledge base edit reaches callers on a versioned agent: pushed to a draft and published, the number following latest_published", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake, { draft: false });

  await client(fake).pushKnowledgeBaseIds(agentId, ["kb-new"]);

  const live = fake.answering(PHONE);
  assert.deepEqual(live.llm.knowledge_base_ids, ["kb-new"]);
  assert.equal(live.binding, "latest_published");
  assert.equal(live.llm.general_prompt, HAND_PROMPT);
});

test("a knowledge base edit refuses to publish someone's unfinished dashboard edits, and leaves the live version untouched", async () => {
  const fake = createFakeRetell();
  const { agentId } = seedSamantha(fake);

  await assert.rejects(
    client(fake).pushKnowledgeBaseIds(agentId, ["kb-new"]),
    /unpublished edits/,
  );
  assert.equal(fake.answering(PHONE).agent.version, 1);
  assert.deepEqual(fake.answering(PHONE).llm.knowledge_base_ids, ["kb-1", "kb-2"]);
});
